define Tristan = Character('Tristan Garcia',bold=True, color="#1e4e9c")
define Zoe = Character('(Zoe Gonzales)', color = "#e6379d")
define Emil = Character('(Emil Navarro)', color ="#ff0000")
define Manager = Character('(Manager)', color="#8f491a")
define Doctor = Character('Doctor', color="#be35e7")
define Girl = Character('Girl', color="#be35e7")
define CrowdM = Character('(Man In Crowd)', color="#ff9100")
define CrowdF = Character('(Woman In Crowd)', color="#ff9100")
define Chessplayer1 = Character('(Chess Player 1)', color="#01ac17")
define Chessplayer2 = Character('(Chess Player 2)', color="#01ac17")
define Commentator = Character('(Commentator)',color="#ffffff")
